from __future__ import annotations

from typing import Protocol

from ..domain import Document


class DocumentRepository(Protocol):
    def create(self, payload: dict) -> Document: ...
    def get(self, identifier: str) -> Document: ...
    def list(self) -> list[Document]: ...
    def update(self, identifier: str, changes: dict) -> Document: ...
    def attach_content(self, identifier: str, key: str, content_type: str, size: int) -> Document: ...
    def delete(self, identifier: str) -> Document: ...


class ObjectStorage(Protocol):
    def put(self, key: str, body: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def signed_get(self, key: str, expires_in: int) -> str | None: ...
    def delete(self, key: str) -> None: ...
